services:
  nats:
    image: nats:latest
    container_name: knwstack-nats
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # Monitoring port
    command: "-js -m 8222" # Enable JetStream and Monitoring
    volumes:
      - nats_data:/data
    restart: always

  nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: knwstack-nui
    ports:
      - "31311:31311"
    environment:
      - NUI_NATS_URL=nats://nats:4222
    depends_on:
      - nats
    restart: always

  nats-box:
    image: natsio/nats-box:latest
    container_name: knwstack-nats-box
    command: "sleep infinity"
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
    restart: always

volumes:
  nats_data:
